# Generated by Django 4.2.4 on 2025-08-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
